import type { Translations } from './types';

export const LETTERS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'L', 'M', 'N', 'Ñ', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'X', 'Y', 'Z']; // 25 letters
export const DEFAULT_TIME = 200; // seconds

export const translations: Translations = {
    es: {
        title: "Pasapalabra IA",
        topic: "Tema del Rosco:",
        educationalLevel: "Nivel Educativo:",
        difficulty: "Dificultad:",
        questionLanguage: "Idioma de las Preguntas:",
        gameTime: "Tiempo de Juego (segundos):",
        easy: "Fácil",
        normal: "Normal",
        hard: "Difícil",
        generateQuestions: "Generar Preguntas",
        loadingQuestions: "Generando preguntas con IA...",
        questionForLetter: "Pregunta para la letra",
        answer: "Tu respuesta:",
        submit: "Responder",
        pass: "Pasapalabra",
        timeLeft: "Tiempo:",
        score: "Aciertos:",
        gameOver: "¡Juego Terminado!",
        finalScore: "Puntuación Final:",
        playAgain: "Jugar de Nuevo",
        correct: "¡Correcto!",
        incorrect: "Incorrecto.",
        correctAnswerWas: "La respuesta correcta era:",
        theme: "Tema",
        lightTheme: "Claro",
        darkTheme: "Oscuro",
        maximize: "Maximizar",
        minimize: "Minimizar",
        questionFontSize: "Tamaño Fuente Pregunta:",
        fontSizeNormal: "Normal",
        fontSizeLarge: "Grande",
        fontSizeExtraLarge: "Extra Grande",
        errorGeneratingQuestions: "Error al generar preguntas. Inténtalo de nuevo.",
        errorLoadingPrefs: "Error cargando preferencias.",
        errorSavingPrefs: "Error guardando preferencias.",
        waitingForAI: "Esperando respuesta de la IA...",
        noQuestionsLoaded: "No se pudieron cargar las preguntas.",
        confirmLeave: "Si sales ahora, perderás el progreso de la partida actual. ¿Estás seguro?",
        pasapalabraInfo: "(Preguntas generadas por IA o introducidas manualmente. Las respuestas son validadas contra la respuesta correcta.)",
        generating: "Generando...",
        letter: "Letra",
        definition: "Definición",
        yourAnswer: "Tu Respuesta",
        status: "Estado",
        pending: "Pendiente",
        answeredCorrect: "Correcta",
        answeredIncorrect: "Incorrecta",
        passed: "Pasada",
        placeholderTopic: "Ej: Biología celular, Historia de España",
        placeholderLevel: "Ej: Secundaria, Bachillerato, Universitario",
        placeholderQuestionLang: "Ej: Español, Català, English, Français",
        summaryRosco: "Resumen del Rosco:",
        footerLab: "Laboratorio de aplicaciones educativas",
        footerAuthor: "Aplicación hecha por Juan José de Haro",
        footerLicense: "Licencia Creative Commons BY-SA",
        reviewQuestions: "Revisar y Editar Preguntas",
        startGame: "Empezar a Jugar",
        question: "Pregunta",
        correctAnswer: "Respuesta Correcta",
        saveRosco: "Guardar este Rosco",
        saving: "Guardando...",
        roscoSavedSuccess: "¡Rosco guardado con éxito!",
        errorSavingRosco: "Error al guardar el rosco.",
        loadSavedRosco: "O Cargar un Rosco Guardado",
        noSavedRoscos: "No tienes roscos guardados.",
        load: "Cargar",
        completeAllFields: "Por favor, completa todos los campos requeridos.",
        generateWithAI: "Generar con IA",
        manualInput: "Introducir Manualmente",
        manualInputTitle: "Introduce las preguntas y respuestas",
        mainMenu: "Menú Principal",
        endGame: "Terminar Partida",
        mute: "Silenciar",
        unmute: "Activar Sonido",
        noQuestionsToSave: "No hay preguntas para guardar. Por favor, genera o introduce las preguntas primero.",
    }
};
